### ISSUE TITLE
Integration with WebThingsIO as add-on for the Gateway

### ISSUE THREAD

**Issue by Utopiah** [samubura/wot-web-simulator#1]
Hi, is there a plan to do so? Also is there a plan to go from simulated result to actually doing it?

PS: found this project via https://github.com/elephantrobotics/jsmycobot

**Comment by samubura** [comment]
Hello,
thanks for your interest in my project. I'm not sure I follow your request, you mean if there is a plan to integrate the visual part of the simulator with the WebThingsIO gateway?

As far as real web-things it has been used with real ones instead of simulated ones acting as a proxy but it is not actually done right now in a clean way, the idea would be to merge real things and simulated ones without distinction to be able to test complex scenarios even if the hardware is not available.

Anyway, this software was developed as a prototype to support some demos, I'm not currently evolving it at the moment so there is no real plan to move this forward but I'll keep in mind your valuable input since the integration with the gateway looks interesting to me!

**Comment by Utopiah** [comment]
> merge real things and simulated ones without distinction to be able to test complex scenarios even if the hardware is not available.

Indeed or add a metadata, even if hijacking an existing field e.g name with a simulated_ prefix.

Anyway I understand the prototyping aspect, just thought it could be an interesting use case, especially for pedagogical purposes but it might indeed be better to stick to real Things still.

**Comment by Utopiah** [comment]
cc @rzr as I remember you worked on a similar simulation project for WoT.

**Comment by rzr** [comment]
This https://github.com/rzr/twins/ ?
